apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: environment/test-01/argocd-apps
    repoURL: 'https://github.com/roypeter/argocd.git'
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
